README.md, server.go, server_test.go
Currently the fragment name is passed via query param. e.g.  `header`
would be `?fragment=header`.
This removes the query param in favor of extending the target url,
creating a unique url for each fragment.
e.g. the `site/header` fragment with a target of
`https://localhost:3000/_view_fragments` would result in a request to
`htttps://localhost:3000/_view_fragments/site/header`
This aligns the behavior of fragments with the behavior of layouts.
=> Use url path instead of query param

cmd/demo/main.go, server.go, server_test.go
This adds basic header forwarding from the layout request to the voltron
response. So any headers set in the request made to the layout that
aren't in the ignore list will be sent as part of the response.
As a default, the ignored headers only contains `content-length`.
=> Add basic header forwarding

.gitignore, cmd/demo/main.go, config.go, pkg/multiplexer/multiplexer_test.go, server.go, server_test.go
This defines a JSON format that can be used to import routes into a
viewproxy server instead of having to define them manually. This is
meant to be used with a lightweight Rails DSL to define pages and their
fragments so viewproxy routes can be auto-generated.
=> Add ability to define routes via JSON

README.md
This also fixes the spelling of `viewproxy` in places.
=> Add philosophy to README

.github/workflows/go.yml, cmd/demo/main.go, pkg/multiplexer/multiplexer.go, pkg/multiplexer/multiplexer_test.go, pkg/multiplexer/proxy.go, pkg/multiplexer/proxy_test.go, pkg/multiplexer/result.go, server.go, server_test.go
This adds a new value to the Server struct, `PassThrough`, which when
set to true, will forward a request as-received to the target server and
proxy the response back to the request.
- Add constructor for viewproxy Server
- Add pass through functionality for GET requests
- Extract result into new file
=> Add proxy pass through functionality for GET requests

server.go
This copies the standard libraries logger interface so any logger that
complies with the interface can be plugged into viewproxy.
=> Use logger interface instead of log.Logger struct

pkg/multiplexer/multiplexer.go, pkg/multiplexer/multiplexer_test.go, server.go, server_test.go
This adds support for sending an `Authorization` header to the target
server when requesting page fragments. This should help prevent
unauthorized access of fragment/layout endpoints.
A timestamp is included as an `X-Authorization-Time` header which is
also part of the HMAC itself, allowing target servers to implement their
own expiration logic.
=> Add support for HMAC request verification

server.go, server_test.go
This adds new field to the `Server` struct, `PreRequest`. This function
is called before the `http.Request` is handled by viewproxy.
This will be useful for logging information like the IP address of the
user requesting the page.
=> Add prerequest callback function to server

config.go, server.go, server_test.go
This adds the ability to load routes from `[]byte` which is useful when using `//go:embed`
=> Add ability to load routes from pre-read JSON files

README.md, cmd/demo/main.go, config.go, fragment.go, pkg/multiplexer/multiplexer.go, pkg/multiplexer/multiplexer_test.go, route.go, route_test.go, server.go, server_test.go
This allows each fragment to be configured with a static map of
key/values, which will be set as tracing attributes when each fragment
is fetched.
See README for updated usage
=> Set tracing attributes for each fragment metadata key/value

pkg/multiplexer/multiplexer.go, pkg/multiplexer/multiplexer_test.go, pkg/multiplexer/result.go, server.go, server_test.go
Extract custom error type for result errors
Currently there are two error types that can come from a multiplexer
request, `Non2xxErr` and `NotFoundErr`. These are both simple error
types implemented via strings. This makes it difficult to extra any
extra information from the errors.
To enable us to expose more data via errors, this introduces a new error
struct, `ResultError`, which embeds the `Result` that caused the Error.
=> Add ability to handle errors

server.go, server_test.go
This adds query param forwarding to fragment requests instead of
silently dropping them.
This accounts for named parameters and does not allow a user passed
query parameter to override a route parameter.
closes https://github.com/BlakeWilliams/viewproxy/issues/8
=> Add query param forwarding to fragment requests

pkg/multiplexer/multiplexer.go
Sometimes URL's can contain secrets that shouldn't be sent to third
parties.
This removes the URL and relies on the new metadata attributes to
identify traces.
=> Remove URL attribute from traces

README.md, fragment.go, go.mod, go.sum, pkg/multiplexer/multiplexer.go, pkg/multiplexer/multiplexer_test.go, pkg/multiplexer/result.go, pkg/multiplexer/server_timing.go, response_builder.go, server.go, server_test.go
This pull request adds support for building a combined [`Server-Timing`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing) header that includes the timings from each of the fragments with a configured prefix.
Setting a `TimingLabel` string on a fragment will cause it to re-format the `Server-Timing` header in the response to have a new name/description for each value from the individual requests.
Generating something like the following for a page with 3 fragments:
=> Add support for aggregating Server-Timing headers

route.go, server.go, server_test.go
This is more flexible, allowing users of viewproxy to log and measure the time spent in each request handled by viewproxy
Closes https://github.com/BlakeWilliams/viewproxy/issues/29
TODO:
=> Expose AroundRequest instead of PreRequest

pkg/multiplexer/server_timing.go, server_test.go
This pull request is a follow on to #34, it adds a `Server-Timing` of the duration of each fragment result that has a `timingLabel` configured.
This timing will give the total request timing for fragment as experienced by viewproxy.
=> Add fragment result duration to server timing header

server.go, server_test.go
This pull request changes `AroundRequest` to be a middleware API that takes a handler and returns a handler.
This also converts `Server` to several `http.Handler`s in the following order:
- `rootHandler` adds overall tracing and sets up the context with route and parameters, exposed via new `GetRoute` and `GetParameters` API for a `Context` for downstream handlers.
- `AroundRequest` optionally adds any domain-specific middleware to request lifecycle
- `requestHandler` serves the request using route/parameters from the context
=> Make AroundRequest a handler to handler middleware API

cmd/demo/main.go, pkg/middleware/logging/logging.go, pkg/middleware/logging/logging_test.go, pkg/multiplexer/fragment.go, pkg/multiplexer/multiplexer.go, pkg/multiplexer/multiplexer_test.go, pkg/multiplexer/tripper.go, server.go, server_test.go
This adds a transport interface that allows consumers of viewproxy to
provide their own logic for fetching fragments.
Instead of providing completely paved paths with logging and
instrumentation this will allow consumers to build their own low-level
logging, instrumentation, http request logic, and more.
A default tripper implementation is provided that delegates to an
`http.Client{}`.
Additionally, the `route`, and `fragment` for the request is provided in
the `request.Context()` so consumers can log or instrument individual
requests.
=> Add multiplexer.Tripper interface

cmd/demo/main.go, server.go, server_test.go
Previously we were only letting the server port be configured and bound the server address to `:3005`.
This pull request changes it so the full server address can be configured to allow bindings like `localhost:3005`.
This allows the tests on macos to skip these warnings when binding to `:PORT` without a host name.
=> Change port config to use full address

pkg/multiplexer/multiplexer_test.go, server.go
This pull request adds a Serve API that takes a `net.Listener`.
This will allow callers to use it directly instead of `ListenAndServe` when they want to manage/configure their own listeners.
=> Expose Serve API that takes a listener

server.go, server_test.go
Currently the target application doesn't know the original request path
that triggered it to run.
This resolves the issue by sending the original request path to each
layout/fragment request via the "X-Viewproxy-Original-Path" header.
=> Add header with original request path to fragment requests

pkg/multiplexer/headers.go, pkg/multiplexer/headers_test.go
This preserves forwarded proto and host headers to handle the case where viewproxy is itself behind one or more proxies.
=> Preserve forwarded proto and host headers

pkg/multiplexer/multiplexer.go, pkg/multiplexer/multiplexer_test.go, pkg/multiplexer/result.go, server.go
This pull request uses the `SecretFilter` to filter the URL included in the `ResultError` message.
Refs #52
=> Filter result error messages using secret filter

README.md, cmd/demo/main.go, response_builder.go, server.go
While using this library we've determined that the title replacement
functionality via headers isn't currently necessary.
=> Remove title replacement functionality

server.go, server_test.go
This pull request tweaks the handling of `X-Viewproxy-Original-Path` to use `Set` instead of `Add` so that the header value is set once and only contains the value generated by `viewproxy`, not a value set on the original request.
=> Use Set instead of Add for original path header

server.go
This will allow consumers of the API to determine why a shutdown failed and
react to it.
=> Forward http.Server shutdown error in viewproxy shutdown

server.go
This pull request adds `ReadTimeout` and `WriteTimeout` configurations to be set by consumers.
=> Allow read/write timeout to be configured

pkg/multiplexer/multiplexer.go, pkg/secretfilter/secretfilter.go, pkg/secretfilter/secretfilter_test.go
This pull request runs all `url.Error` request errors through the secretfilter.
This prevents them from surfacing unfiltered values.
=> Filter url errors using secretfilter package

pkg/multiplexer/multiplexer.go
This prevents goroutines stacking up when all fragment requests generate an error and pushing to the error channel would block and also hold up the wait group.
=> Use a buffered error channel and defer closing it

cmd/demo/main.go, pkg/middleware/logging/logging.go, pkg/middleware/logging/logging_test.go, server.go, server_test.go
This migrates the existing pass through proxy mode to utilize the
built-in `httputil.ReverseProxy` module.
This causes some of our logging to no longer work but gives us a more
reliable, community tested reverse proxy.
=> Migrate custom proxy to httputil.ReverseProxy

README.md, cmd/demo/main.go, pkg/multiplexer/headers.go, pkg/multiplexer/result.go, pkg/multiplexer/server_timing.go, pkg/routeimporter/http_test.go, response_builder.go, server.go, server_test.go
This pull request adds a new `AroundResponse` middleware that runs after the fragment results have completed but before the response is written.
This will give consumers the ability to configure all the headers and response body before they are sent on the response while accessing the headers on the individual fragment responses.
This removes the `IgnoreHeader` and `OnError` APIs since this new API gives a broader option for stripping, updating, adding headers, and serving error pages.
I chose to just re-use the existing `http.Handler` pattern instead of adding something new for consistency with the full request middleware we already have (`AroundRequest`).
The server timing middleware was updated to use this new API which felt cleaner. This felt like something likely to be useful via …
=> Add middleware for generating response after fragments are fetched

server.go, server_test.go
I believe this existed before consumers could use `AroundRequest` to implement it so it seems worth removing now and ensure consumers do it instead.
=> Remove ping endpoint

pkg/fragment/definition.go, pkg/fragment/definition_test.go, server.go, server_test.go
As-is, when Voltron processes a url containing `%2f` it is read as an
actual `/` by the router due to the use of `request.URL.Path` instead of
`request.URL.EscapedPath()` which includes the escapes correctly.
This fixes the route matching issue by using `EscapedPath` instead of
`Path`.
Additionally, the parameters being passed to the target server were
being double escaped since the `request.Path` was being set to include
the `%2f` escape. To resolve this, `request.Path` is set to the
*unescaped* path, and `request.RawPath` is set to the escaped path. This
generates the expected URL with the `%2f` escape instead of `%252`.
Due to `url.PathUnescape` possibly returning an error, this introduces
another potential way to fail to serve a request and will result in a
panic if it does return an …
=> Fix uri encoding issue for named fragments

pkg/fragment/definition.go, pkg/fragment/definition_test.go, pkg/multiplexer/multiplexer.go, pkg/multiplexer/multiplexer_test.go, pkg/multiplexer/requestable.go, pkg/multiplexer/result.go, pkg/secretfilter/secretfilter.go, pkg/secretfilter/secretfilter_test.go
This pull request uses the template fragment definition URL as the one surfaced in errors passed through the secret filter.
This ensures definitions such as `/route/:user/:status` will not surface the replaced values such as `/route/kevin/friday` in result/url errors.
This makes it consistent with the old behavior where `/route?user=kevin&status=friday` was surfaced as `/route?user=FILTERED&status=FILTERED`.
=> Filter named route params from URLs

route.go, server.go, server_test.go
This removes support for legacy routes that relied on the query
parameter logic instead of named parameters.
=> Remove legacy route support

server.go, server_test.go
As-is viewproxy always creates a new trace even if it was passed the headers indicating that it should continue an existing trace.
This adds support for continuing and existing trace by using the TextMapPropagator's `Extract` method on the request headers.
=> Re-use existing trace when possible

internal/tracing/tracing.go
This pull request changes the tracing error handling to log them via `Println`, instead of `Fatalln`.
Logging interface implementations may call `exit` on fatal errors and tracing errors don't feel like they rise to that level of seriousness and can just be logged less severly.
=> Don't treat tracing errors as fatal

pkg/multiplexer/multiplexer.go
I noticed we were overwriting the root level context variable in the requestable loop for the context we eventually wait on after starting the go routines:
https://github.com/BlakeWilliams/viewproxy/blob/d4540cae717b7a3101be386179585d5b0440ab32/pkg/multiplexer/multiplexer.go#L135-L136
It seemed best not to overwrite this value with request specific state and they wait on the done channel for the final request value.
I don't have any evidence this is causing any issues but just noticed it while reviewing the multiplexer code.
=> Don't overwrite context variable in request loop

pkg/multiplexer/multiplexer.go
I noticed recently while grepping for tracing attributes we were using the `KeyValue` API when the `String` API would seem to be a bit nicer and cleaner.
=> Use nicer attribute.String API for metadata

pkg/multiplexer/multiplexer.go, pkg/multiplexer/multiplexer_test.go
If a request is canceled by the client, a timeout error is not appropriate because the server may be unable to write a response.
Returning a cancellation error will allow the server to ignore the requests
=> Detect request cancellations and return new error type
